// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
class MsgBody;
class MsgBodyDefaultTypeInternal;
extern MsgBodyDefaultTypeInternal _MsgBody_default_instance_;
class MsgBody_Request;
class MsgBody_RequestDefaultTypeInternal;
extern MsgBody_RequestDefaultTypeInternal _MsgBody_Request_default_instance_;
class MsgBody_Response;
class MsgBody_ResponseDefaultTypeInternal;
extern MsgBody_ResponseDefaultTypeInternal _MsgBody_Response_default_instance_;
class MsgHead;
class MsgHeadDefaultTypeInternal;
extern MsgHeadDefaultTypeInternal _MsgHead_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MsgBody* Arena::CreateMaybeMessage<::MsgBody>(Arena*);
template<> ::MsgBody_Request* Arena::CreateMaybeMessage<::MsgBody_Request>(Arena*);
template<> ::MsgBody_Response* Arena::CreateMaybeMessage<::MsgBody_Response>(Arena*);
template<> ::MsgHead* Arena::CreateMaybeMessage<::MsgHead>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MsgHead PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgHead) */ {
 public:
  inline MsgHead() : MsgHead(nullptr) {};
  virtual ~MsgHead();

  MsgHead(const MsgHead& from);
  MsgHead(MsgHead&& from) noexcept
    : MsgHead() {
    *this = ::std::move(from);
  }

  inline MsgHead& operator=(const MsgHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgHead& operator=(MsgHead&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgHead& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgHead* internal_default_instance() {
    return reinterpret_cast<const MsgHead*>(
               &_MsgHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MsgHead& a, MsgHead& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgHead* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgHead* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgHead* New() const final {
    return CreateMaybeMessage<MsgHead>(nullptr);
  }

  MsgHead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgHead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgHead& from);
  void MergeFrom(const MsgHead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgHead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgHead";
  }
  protected:
  explicit MsgHead(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCmdFieldNumber = 1,
    kSeqFieldNumber = 2,
    kLenFieldNumber = 3,
  };
  // fixed32 cmd = 1;
  void clear_cmd();
  ::PROTOBUF_NAMESPACE_ID::uint32 cmd() const;
  void set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cmd() const;
  void _internal_set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // fixed32 seq = 2;
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::uint32 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // sfixed32 len = 3;
  void clear_len();
  ::PROTOBUF_NAMESPACE_ID::int32 len() const;
  void set_len(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_len() const;
  void _internal_set_len(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgHead)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cmd_;
  ::PROTOBUF_NAMESPACE_ID::uint32 seq_;
  ::PROTOBUF_NAMESPACE_ID::int32 len_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class MsgBody_Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgBody.Request) */ {
 public:
  inline MsgBody_Request() : MsgBody_Request(nullptr) {};
  virtual ~MsgBody_Request();

  MsgBody_Request(const MsgBody_Request& from);
  MsgBody_Request(MsgBody_Request&& from) noexcept
    : MsgBody_Request() {
    *this = ::std::move(from);
  }

  inline MsgBody_Request& operator=(const MsgBody_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgBody_Request& operator=(MsgBody_Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgBody_Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgBody_Request* internal_default_instance() {
    return reinterpret_cast<const MsgBody_Request*>(
               &_MsgBody_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MsgBody_Request& a, MsgBody_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgBody_Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgBody_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgBody_Request* New() const final {
    return CreateMaybeMessage<MsgBody_Request>(nullptr);
  }

  MsgBody_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgBody_Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgBody_Request& from);
  void MergeFrom(const MsgBody_Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBody_Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgBody.Request";
  }
  protected:
  explicit MsgBody_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRouteFieldNumber = 2,
    kRouteIdFieldNumber = 1,
  };
  // string route = 2;
  void clear_route();
  const std::string& route() const;
  void set_route(const std::string& value);
  void set_route(std::string&& value);
  void set_route(const char* value);
  void set_route(const char* value, size_t size);
  std::string* mutable_route();
  std::string* release_route();
  void set_allocated_route(std::string* route);
  private:
  const std::string& _internal_route() const;
  void _internal_set_route(const std::string& value);
  std::string* _internal_mutable_route();
  public:

  // uint32 route_id = 1;
  void clear_route_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 route_id() const;
  void set_route_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_route_id() const;
  void _internal_set_route_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgBody.Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr route_;
  ::PROTOBUF_NAMESPACE_ID::uint32 route_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class MsgBody_Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgBody.Response) */ {
 public:
  inline MsgBody_Response() : MsgBody_Response(nullptr) {};
  virtual ~MsgBody_Response();

  MsgBody_Response(const MsgBody_Response& from);
  MsgBody_Response(MsgBody_Response&& from) noexcept
    : MsgBody_Response() {
    *this = ::std::move(from);
  }

  inline MsgBody_Response& operator=(const MsgBody_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgBody_Response& operator=(MsgBody_Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgBody_Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgBody_Response* internal_default_instance() {
    return reinterpret_cast<const MsgBody_Response*>(
               &_MsgBody_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MsgBody_Response& a, MsgBody_Response& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgBody_Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgBody_Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgBody_Response* New() const final {
    return CreateMaybeMessage<MsgBody_Response>(nullptr);
  }

  MsgBody_Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgBody_Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgBody_Response& from);
  void MergeFrom(const MsgBody_Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBody_Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgBody.Response";
  }
  protected:
  explicit MsgBody_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // bytes msg = 2;
  void clear_msg();
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // int32 code = 1;
  void clear_code();
  ::PROTOBUF_NAMESPACE_ID::int32 code() const;
  void set_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_code() const;
  void _internal_set_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgBody.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  ::PROTOBUF_NAMESPACE_ID::int32 code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class MsgBody PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgBody) */ {
 public:
  inline MsgBody() : MsgBody(nullptr) {};
  virtual ~MsgBody();

  MsgBody(const MsgBody& from);
  MsgBody(MsgBody&& from) noexcept
    : MsgBody() {
    *this = ::std::move(from);
  }

  inline MsgBody& operator=(const MsgBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgBody& operator=(MsgBody&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgBody& default_instance();

  enum MsgTypeCase {
    kReqTarget = 1,
    kRspResult = 2,
    MSG_TYPE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgBody* internal_default_instance() {
    return reinterpret_cast<const MsgBody*>(
               &_MsgBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MsgBody& a, MsgBody& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgBody* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgBody* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgBody* New() const final {
    return CreateMaybeMessage<MsgBody>(nullptr);
  }

  MsgBody* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgBody>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgBody& from);
  void MergeFrom(const MsgBody& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgBody* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgBody";
  }
  protected:
  explicit MsgBody(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef MsgBody_Request Request;
  typedef MsgBody_Response Response;

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kAddOnFieldNumber = 4,
    kTraceIdFieldNumber = 5,
    kReqTargetFieldNumber = 1,
    kRspResultFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // bytes add_on = 4;
  void clear_add_on();
  const std::string& add_on() const;
  void set_add_on(const std::string& value);
  void set_add_on(std::string&& value);
  void set_add_on(const char* value);
  void set_add_on(const void* value, size_t size);
  std::string* mutable_add_on();
  std::string* release_add_on();
  void set_allocated_add_on(std::string* add_on);
  private:
  const std::string& _internal_add_on() const;
  void _internal_set_add_on(const std::string& value);
  std::string* _internal_mutable_add_on();
  public:

  // string trace_id = 5;
  void clear_trace_id();
  const std::string& trace_id() const;
  void set_trace_id(const std::string& value);
  void set_trace_id(std::string&& value);
  void set_trace_id(const char* value);
  void set_trace_id(const char* value, size_t size);
  std::string* mutable_trace_id();
  std::string* release_trace_id();
  void set_allocated_trace_id(std::string* trace_id);
  private:
  const std::string& _internal_trace_id() const;
  void _internal_set_trace_id(const std::string& value);
  std::string* _internal_mutable_trace_id();
  public:

  // .MsgBody.Request req_target = 1;
  bool has_req_target() const;
  private:
  bool _internal_has_req_target() const;
  public:
  void clear_req_target();
  const ::MsgBody_Request& req_target() const;
  ::MsgBody_Request* release_req_target();
  ::MsgBody_Request* mutable_req_target();
  void set_allocated_req_target(::MsgBody_Request* req_target);
  private:
  const ::MsgBody_Request& _internal_req_target() const;
  ::MsgBody_Request* _internal_mutable_req_target();
  public:
  void unsafe_arena_set_allocated_req_target(
      ::MsgBody_Request* req_target);
  ::MsgBody_Request* unsafe_arena_release_req_target();

  // .MsgBody.Response rsp_result = 2;
  bool has_rsp_result() const;
  private:
  bool _internal_has_rsp_result() const;
  public:
  void clear_rsp_result();
  const ::MsgBody_Response& rsp_result() const;
  ::MsgBody_Response* release_rsp_result();
  ::MsgBody_Response* mutable_rsp_result();
  void set_allocated_rsp_result(::MsgBody_Response* rsp_result);
  private:
  const ::MsgBody_Response& _internal_rsp_result() const;
  ::MsgBody_Response* _internal_mutable_rsp_result();
  public:
  void unsafe_arena_set_allocated_rsp_result(
      ::MsgBody_Response* rsp_result);
  ::MsgBody_Response* unsafe_arena_release_rsp_result();

  void clear_msg_type();
  MsgTypeCase msg_type_case() const;
  // @@protoc_insertion_point(class_scope:MsgBody)
 private:
  class _Internal;
  void set_has_req_target();
  void set_has_rsp_result();

  inline bool has_msg_type() const;
  inline void clear_has_msg_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr add_on_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_id_;
  union MsgTypeUnion {
    MsgTypeUnion() {}
    ::MsgBody_Request* req_target_;
    ::MsgBody_Response* rsp_result_;
  } msg_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MsgHead

// fixed32 cmd = 1;
inline void MsgHead::clear_cmd() {
  cmd_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MsgHead::_internal_cmd() const {
  return cmd_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MsgHead::cmd() const {
  // @@protoc_insertion_point(field_get:MsgHead.cmd)
  return _internal_cmd();
}
inline void MsgHead::_internal_set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cmd_ = value;
}
inline void MsgHead::set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cmd(value);
  // @@protoc_insertion_point(field_set:MsgHead.cmd)
}

// fixed32 seq = 2;
inline void MsgHead::clear_seq() {
  seq_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MsgHead::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MsgHead::seq() const {
  // @@protoc_insertion_point(field_get:MsgHead.seq)
  return _internal_seq();
}
inline void MsgHead::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  seq_ = value;
}
inline void MsgHead::set_seq(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:MsgHead.seq)
}

// sfixed32 len = 3;
inline void MsgHead::clear_len() {
  len_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHead::_internal_len() const {
  return len_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHead::len() const {
  // @@protoc_insertion_point(field_get:MsgHead.len)
  return _internal_len();
}
inline void MsgHead::_internal_set_len(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  len_ = value;
}
inline void MsgHead::set_len(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_len(value);
  // @@protoc_insertion_point(field_set:MsgHead.len)
}

// -------------------------------------------------------------------

// MsgBody_Request

// uint32 route_id = 1;
inline void MsgBody_Request::clear_route_id() {
  route_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MsgBody_Request::_internal_route_id() const {
  return route_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MsgBody_Request::route_id() const {
  // @@protoc_insertion_point(field_get:MsgBody.Request.route_id)
  return _internal_route_id();
}
inline void MsgBody_Request::_internal_set_route_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  route_id_ = value;
}
inline void MsgBody_Request::set_route_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_route_id(value);
  // @@protoc_insertion_point(field_set:MsgBody.Request.route_id)
}

// string route = 2;
inline void MsgBody_Request::clear_route() {
  route_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgBody_Request::route() const {
  // @@protoc_insertion_point(field_get:MsgBody.Request.route)
  return _internal_route();
}
inline void MsgBody_Request::set_route(const std::string& value) {
  _internal_set_route(value);
  // @@protoc_insertion_point(field_set:MsgBody.Request.route)
}
inline std::string* MsgBody_Request::mutable_route() {
  // @@protoc_insertion_point(field_mutable:MsgBody.Request.route)
  return _internal_mutable_route();
}
inline const std::string& MsgBody_Request::_internal_route() const {
  return route_.Get();
}
inline void MsgBody_Request::_internal_set_route(const std::string& value) {
  
  route_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgBody_Request::set_route(std::string&& value) {
  
  route_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.Request.route)
}
inline void MsgBody_Request::set_route(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  route_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MsgBody.Request.route)
}
inline void MsgBody_Request::set_route(const char* value,
    size_t size) {
  
  route_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MsgBody.Request.route)
}
inline std::string* MsgBody_Request::_internal_mutable_route() {
  
  return route_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgBody_Request::release_route() {
  // @@protoc_insertion_point(field_release:MsgBody.Request.route)
  return route_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgBody_Request::set_allocated_route(std::string* route) {
  if (route != nullptr) {
    
  } else {
    
  }
  route_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), route,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MsgBody.Request.route)
}

// -------------------------------------------------------------------

// MsgBody_Response

// int32 code = 1;
inline void MsgBody_Response::clear_code() {
  code_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgBody_Response::_internal_code() const {
  return code_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgBody_Response::code() const {
  // @@protoc_insertion_point(field_get:MsgBody.Response.code)
  return _internal_code();
}
inline void MsgBody_Response::_internal_set_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  code_ = value;
}
inline void MsgBody_Response::set_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:MsgBody.Response.code)
}

// bytes msg = 2;
inline void MsgBody_Response::clear_msg() {
  msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgBody_Response::msg() const {
  // @@protoc_insertion_point(field_get:MsgBody.Response.msg)
  return _internal_msg();
}
inline void MsgBody_Response::set_msg(const std::string& value) {
  _internal_set_msg(value);
  // @@protoc_insertion_point(field_set:MsgBody.Response.msg)
}
inline std::string* MsgBody_Response::mutable_msg() {
  // @@protoc_insertion_point(field_mutable:MsgBody.Response.msg)
  return _internal_mutable_msg();
}
inline const std::string& MsgBody_Response::_internal_msg() const {
  return msg_.Get();
}
inline void MsgBody_Response::_internal_set_msg(const std::string& value) {
  
  msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgBody_Response::set_msg(std::string&& value) {
  
  msg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.Response.msg)
}
inline void MsgBody_Response::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MsgBody.Response.msg)
}
inline void MsgBody_Response::set_msg(const void* value,
    size_t size) {
  
  msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MsgBody.Response.msg)
}
inline std::string* MsgBody_Response::_internal_mutable_msg() {
  
  return msg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgBody_Response::release_msg() {
  // @@protoc_insertion_point(field_release:MsgBody.Response.msg)
  return msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgBody_Response::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MsgBody.Response.msg)
}

// -------------------------------------------------------------------

// MsgBody

// .MsgBody.Request req_target = 1;
inline bool MsgBody::_internal_has_req_target() const {
  return msg_type_case() == kReqTarget;
}
inline bool MsgBody::has_req_target() const {
  return _internal_has_req_target();
}
inline void MsgBody::set_has_req_target() {
  _oneof_case_[0] = kReqTarget;
}
inline void MsgBody::clear_req_target() {
  if (_internal_has_req_target()) {
    if (GetArena() == nullptr) {
      delete msg_type_.req_target_;
    }
    clear_has_msg_type();
  }
}
inline ::MsgBody_Request* MsgBody::release_req_target() {
  // @@protoc_insertion_point(field_release:MsgBody.req_target)
  if (_internal_has_req_target()) {
    clear_has_msg_type();
      ::MsgBody_Request* temp = msg_type_.req_target_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_type_.req_target_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::MsgBody_Request& MsgBody::_internal_req_target() const {
  return _internal_has_req_target()
      ? *msg_type_.req_target_
      : *reinterpret_cast< ::MsgBody_Request*>(&::_MsgBody_Request_default_instance_);
}
inline const ::MsgBody_Request& MsgBody::req_target() const {
  // @@protoc_insertion_point(field_get:MsgBody.req_target)
  return _internal_req_target();
}
inline ::MsgBody_Request* MsgBody::unsafe_arena_release_req_target() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MsgBody.req_target)
  if (_internal_has_req_target()) {
    clear_has_msg_type();
    ::MsgBody_Request* temp = msg_type_.req_target_;
    msg_type_.req_target_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MsgBody::unsafe_arena_set_allocated_req_target(::MsgBody_Request* req_target) {
  clear_msg_type();
  if (req_target) {
    set_has_req_target();
    msg_type_.req_target_ = req_target;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MsgBody.req_target)
}
inline ::MsgBody_Request* MsgBody::_internal_mutable_req_target() {
  if (!_internal_has_req_target()) {
    clear_msg_type();
    set_has_req_target();
    msg_type_.req_target_ = CreateMaybeMessage< ::MsgBody_Request >(GetArena());
  }
  return msg_type_.req_target_;
}
inline ::MsgBody_Request* MsgBody::mutable_req_target() {
  // @@protoc_insertion_point(field_mutable:MsgBody.req_target)
  return _internal_mutable_req_target();
}

// .MsgBody.Response rsp_result = 2;
inline bool MsgBody::_internal_has_rsp_result() const {
  return msg_type_case() == kRspResult;
}
inline bool MsgBody::has_rsp_result() const {
  return _internal_has_rsp_result();
}
inline void MsgBody::set_has_rsp_result() {
  _oneof_case_[0] = kRspResult;
}
inline void MsgBody::clear_rsp_result() {
  if (_internal_has_rsp_result()) {
    if (GetArena() == nullptr) {
      delete msg_type_.rsp_result_;
    }
    clear_has_msg_type();
  }
}
inline ::MsgBody_Response* MsgBody::release_rsp_result() {
  // @@protoc_insertion_point(field_release:MsgBody.rsp_result)
  if (_internal_has_rsp_result()) {
    clear_has_msg_type();
      ::MsgBody_Response* temp = msg_type_.rsp_result_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_type_.rsp_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::MsgBody_Response& MsgBody::_internal_rsp_result() const {
  return _internal_has_rsp_result()
      ? *msg_type_.rsp_result_
      : *reinterpret_cast< ::MsgBody_Response*>(&::_MsgBody_Response_default_instance_);
}
inline const ::MsgBody_Response& MsgBody::rsp_result() const {
  // @@protoc_insertion_point(field_get:MsgBody.rsp_result)
  return _internal_rsp_result();
}
inline ::MsgBody_Response* MsgBody::unsafe_arena_release_rsp_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:MsgBody.rsp_result)
  if (_internal_has_rsp_result()) {
    clear_has_msg_type();
    ::MsgBody_Response* temp = msg_type_.rsp_result_;
    msg_type_.rsp_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void MsgBody::unsafe_arena_set_allocated_rsp_result(::MsgBody_Response* rsp_result) {
  clear_msg_type();
  if (rsp_result) {
    set_has_rsp_result();
    msg_type_.rsp_result_ = rsp_result;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MsgBody.rsp_result)
}
inline ::MsgBody_Response* MsgBody::_internal_mutable_rsp_result() {
  if (!_internal_has_rsp_result()) {
    clear_msg_type();
    set_has_rsp_result();
    msg_type_.rsp_result_ = CreateMaybeMessage< ::MsgBody_Response >(GetArena());
  }
  return msg_type_.rsp_result_;
}
inline ::MsgBody_Response* MsgBody::mutable_rsp_result() {
  // @@protoc_insertion_point(field_mutable:MsgBody.rsp_result)
  return _internal_mutable_rsp_result();
}

// bytes data = 3;
inline void MsgBody::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgBody::data() const {
  // @@protoc_insertion_point(field_get:MsgBody.data)
  return _internal_data();
}
inline void MsgBody::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:MsgBody.data)
}
inline std::string* MsgBody::mutable_data() {
  // @@protoc_insertion_point(field_mutable:MsgBody.data)
  return _internal_mutable_data();
}
inline const std::string& MsgBody::_internal_data() const {
  return data_.Get();
}
inline void MsgBody::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgBody::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.data)
}
inline void MsgBody::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MsgBody.data)
}
inline void MsgBody::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MsgBody.data)
}
inline std::string* MsgBody::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgBody::release_data() {
  // @@protoc_insertion_point(field_release:MsgBody.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgBody::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MsgBody.data)
}

// bytes add_on = 4;
inline void MsgBody::clear_add_on() {
  add_on_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgBody::add_on() const {
  // @@protoc_insertion_point(field_get:MsgBody.add_on)
  return _internal_add_on();
}
inline void MsgBody::set_add_on(const std::string& value) {
  _internal_set_add_on(value);
  // @@protoc_insertion_point(field_set:MsgBody.add_on)
}
inline std::string* MsgBody::mutable_add_on() {
  // @@protoc_insertion_point(field_mutable:MsgBody.add_on)
  return _internal_mutable_add_on();
}
inline const std::string& MsgBody::_internal_add_on() const {
  return add_on_.Get();
}
inline void MsgBody::_internal_set_add_on(const std::string& value) {
  
  add_on_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgBody::set_add_on(std::string&& value) {
  
  add_on_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.add_on)
}
inline void MsgBody::set_add_on(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  add_on_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MsgBody.add_on)
}
inline void MsgBody::set_add_on(const void* value,
    size_t size) {
  
  add_on_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MsgBody.add_on)
}
inline std::string* MsgBody::_internal_mutable_add_on() {
  
  return add_on_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgBody::release_add_on() {
  // @@protoc_insertion_point(field_release:MsgBody.add_on)
  return add_on_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgBody::set_allocated_add_on(std::string* add_on) {
  if (add_on != nullptr) {
    
  } else {
    
  }
  add_on_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), add_on,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MsgBody.add_on)
}

// string trace_id = 5;
inline void MsgBody::clear_trace_id() {
  trace_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgBody::trace_id() const {
  // @@protoc_insertion_point(field_get:MsgBody.trace_id)
  return _internal_trace_id();
}
inline void MsgBody::set_trace_id(const std::string& value) {
  _internal_set_trace_id(value);
  // @@protoc_insertion_point(field_set:MsgBody.trace_id)
}
inline std::string* MsgBody::mutable_trace_id() {
  // @@protoc_insertion_point(field_mutable:MsgBody.trace_id)
  return _internal_mutable_trace_id();
}
inline const std::string& MsgBody::_internal_trace_id() const {
  return trace_id_.Get();
}
inline void MsgBody::_internal_set_trace_id(const std::string& value) {
  
  trace_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgBody::set_trace_id(std::string&& value) {
  
  trace_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MsgBody.trace_id)
}
inline void MsgBody::set_trace_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trace_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:MsgBody.trace_id)
}
inline void MsgBody::set_trace_id(const char* value,
    size_t size) {
  
  trace_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MsgBody.trace_id)
}
inline std::string* MsgBody::_internal_mutable_trace_id() {
  
  return trace_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgBody::release_trace_id() {
  // @@protoc_insertion_point(field_release:MsgBody.trace_id)
  return trace_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgBody::set_allocated_trace_id(std::string* trace_id) {
  if (trace_id != nullptr) {
    
  } else {
    
  }
  trace_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trace_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MsgBody.trace_id)
}

inline bool MsgBody::has_msg_type() const {
  return msg_type_case() != MSG_TYPE_NOT_SET;
}
inline void MsgBody::clear_has_msg_type() {
  _oneof_case_[0] = MSG_TYPE_NOT_SET;
}
inline MsgBody::MsgTypeCase MsgBody::msg_type_case() const {
  return MsgBody::MsgTypeCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
